services:
   transport_socket:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/transport-socket:${TRANSPORT_SOCKET_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${TRANSPORT_SOCKET_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${TRANSPORT_SOCKET_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    env_file:
      - ../../global.env
    environment:
      JWKS_URI: http://fusionauth:9011/.well-known/jwks.json
      MAX_RETRIES: ${ACK_MAX_RETRIES}