services:
  bff:
    image: ${DOCKER_REGISTRY_URL}/${org}/bff:${BFF_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${BFF_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${BFF_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      BFF_BASE_URL: http://bff:3000
      EXCEL_PARSER_URL: http://excel-parser:8000
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/bff?sslmode=disable&connect_timeout=100"
      JWKS_URI: ${APP_JWKS_URI}
      MINIO_PDF_BUCKET: bff
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_ENDPOINT: "cdn-api.${DOMAIN_NAME}"
      MINIO_PORT: 443
      MINIO_SECURE_CONN: "True"
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PDF_PARSER_BASE_URL:  ${DOMAIN_SCHEME:-https}://pdf-parser.${DOMAIN_NAME}
      PDF_SPLIT: '50'
      REDIS_DB: 8
      REDIS_HOST: redis
      REDIS_PORT: 6379
      USER_SERVICE_BASE_URL: http://user_service:3000
      OUTBOUND_BASE_URL: http://inboundjs:3000/outbound
      TRANSPORT_SOCKET_BASE_URL: http://transport-socket:3000
      UCI_APIS_BASE_URL: http://uci-apis:3000
      ULCA_API_KEY: ${ULCA_API_KEY}
      ULCA_CONFIG_URL: ${ULCA_CONFIG_URL}
      ULCA_USER_ID: ${ULCA_USER_ID}
      YT_PARSER_URL: http://yt-parser:8000
      CHAT_WITH_DOCS_ORG_OWNER_EMAIL: ${CHAT_WITH_DOCS_ORG_OWNER_EMAIL}
      CHAT_WITH_DOCS_ORG_OWNER_PASSWORD: ${CHAT_WITH_DOCS_ORG_OWNER_PASSWORD}
      CHAT_WITH_DOCS_PASSWORD_KEY: ${CHAT_WITH_DOCS_PASSWORD_KEY}
      CHAT_WITH_DOCS_ORG_ID: ${CHAT_WITH_DOCS_ORG_ID}
      REGISTRY_URL: ${REGISTRY_URL}
      INBOUNDJS_BASE_URL: http://inboundjs:3000
      WEATHER_VISUAL_CROSSING_BASE_URL: ${WEATHER_VISUAL_CROSSING_BASE_URL}
      WEATHER_VISUAL_CROSSING_API_KEY: ${WEATHER_VISUAL_CROSSING_API_KEY}
      DOCUMENT_SERVICE_BASE_URL:  ${DOMAIN_SCHEME:-https}://document-service.${DOMAIN_NAME}
      AZURE_URL: ${AZURE_URL}
      USER_SERVICE_ADMIN_API_KEY: ${USER_SERVICE_ADMIN_API_KEY}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
