services:
  bff:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/bff:${BFF_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${BFF_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${BFF_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      CONFIDENCE_SCORE_THRESHOLD: ${CONFIDENCE_SCORE_THRESHOLD:-0}
      LIMIT_ON_WADWAANI_RESPONSE: ${LIMIT_ON_WADWAANI_RESPONSE:-5}
      PEST_IDENTIFICATION_API_KEY: ${PEST_IDENTIFICATION_API_KEY}
      PEST_IDENTIFICATION_API_URL: ${PEST_IDENTIFICATION_API_URL}
      RAJAI_SEWADWAAR_SCHEME_URL: ${RAJAI_SEWADWAAR_SCHEME_URL}
      RAJAI_SEWADWAAR_PASSWORD: ${RAJAI_SEWADWAAR_PASSWORD}
      RAJAI_SEWADWAAR_USER: ${RAJAI_SEWADWAAR_USER}
      RAJAI_SEWADWAAR_SRVNM: ${RAJAI_SEWADWAAR_SRVNM}
      USER_SERVICE_ADMIN_API_KEY: ${USER_SERVICE_ADMIN_API_KEY}
