services:
  deployer:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/deployer:${DEPLOYER_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${DEPLOYER_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${DEPLOYER_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    environment:
      PWA_REPO: ${DEPLOYER_PWA_REPO}
      VERCEL_CONFIG_JWKS_URI: ${VERCEL_CONFIG_JWKS_URI}
      VERCEL_CONFIG_USER_SERVICE_APP_ID: ${VERCEL_CONFIG_USER_SERVICE_APP_ID}
      VERCEL_CONFIG_USER_SERVICE_URL: ${VERCEL_CONFIG_USER_SERVICE_URL}
      VERCEL_TOKEN: ${DEPLOYER_VERCEL_TOKEN}