  services:
    autotune:
      image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/autotune:${AUTOTUNE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      mem_limit: ${AUTOTUNE_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
      cpus: ${AUTOTUNE_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
      command: bash -c "poetry install && python manage.py database && python manage.py runserver 0.0.0.0:8000"
      environment:
        CELERY_MAX_RETRIES: ${CELERY_MAX_RETRIES:-3}
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        GITHUB_PAT: ${GITHUB_PAT}

    autotune_celery_worker:
      image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/autotune:${AUTOTUNE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      mem_limit: ${AUTOTUNE_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
      cpus: ${AUTOTUNE_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
      command: bash -c "poetry install && celery -A autotune worker --loglevel=info -P gevent"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
      environment:
        CELERY_MAX_RETRIES: ${CELERY_MAX_RETRIES:-3}
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        GITHUB_PAT: ${GITHUB_PAT}