services:
  yt_parser:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/yt-parser:${YT_PARSER_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: always
    mem_limit: ${YT_PARSER_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${YT_PARSER_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    env_file:
      - ../../global.env
    environment:
      ASR_SERVICE_PRIORITY: ${ASR_SERVICE_PRIORITY}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      YOUTUBE_DATA_API_KEY: ${YOUTUBE_DATA_API_KEY}
    depends_on:
      - redis

  yt_parser_celery_worker:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/yt-parser:${YT_PARSER_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    command:  celery -A worker worker -P gevent --loglevel=info   
    restart: always
    mem_limit: ${YT_PARSER_CELERY_WORKER_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${YT_PARSER_CELERY_WORKER_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    env_file:
      - ../../global.env
    environment:
      ASR_SERVICE_PRIORITY: ${ASR_SERVICE_PRIORITY}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
      YOUTUBE_DATA_API_KEY: ${YOUTUBE_DATA_API_KEY}
    depends_on:
      - redis
  