  services:
    ai_tools_proxy:
      image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/ai-tools-proxy:${AI_TOOLS_PROXY_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
      restart: always
      mem_limit: ${AI_TOOLS_PROXY_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
      cpus: ${AI_TOOLS_PROXY_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
      environment:
        DEFAULT_RETRY_COUNT: ${DEFAULT_RETRY_COUNT:-3}
        DEFAULT_TIMEOUT: ${DEFAULT_TIMEOUT:-2000}