volumes:
  vault:

services:
  vault:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    restart: always
    env_file:
      - ../../global.env
    environment:
      VAULT_USERNAME: ${VAULT_USERNAME:?VAULT_USERNAME is not set}
      VAULT_PASSWORD: ${VAULT_PASSWORD:?VAULT_PASSWORD is not set}
    volumes:
      - vault:/vault/file
      - ./vault.json:/vault/config/vault.json
      - ./admin-policy.hcl:/vault/policies/admin-policy.hcl
      - ./vault-init.sh:/vault-init.sh
      - ../../.env:/bhasai/.env
      - ./:/bhasai/
    cap_add:
      - IPC_LOCK
    command: sh -c "bash vault-init.sh" 
