services:  
  dataset_service:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/dataset-service:${DATASET_SERVICE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${DATASET_SERVICE_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${DATASET_SERVICE_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    