services:
  nodehub:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/nodehub:${NODEHUB_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    mem_limit: ${NODEHUB_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${NODEHUB_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    restart: always
    environment:
      REGISTRY_BASE_URL: ${REGISTRY_BASE_URL}