apiVersion: 1
contactPoints:
    - orgId: 1
      name: Discord
      receivers:
        - uid: b1889638-73d4-4799-a1b1-ca5b2b6b6bcc
          type: discord
          settings:
            message: '{{ template "discord-template" . }}'
            url: $GRAFANA_DISCORD_WEBHOOK_URL
            use_discord_username: true
          disableResolveMessage: false
policies:
    - orgId: 1
      receiver: Discord
      group_by:
        - grafana_folder
        - alertname
