# config file version
apiVersion: 1

templates:
  - orgId: 1
    name: discord-template
    template: |
          {{ define "discord-template" }}
          {{- $AnsiColor := ""  -}}
          {{ range .Alerts }}
          {{-  if eq .Status "resolved" -}}
          {{- $AnsiColor = "\u001b[1;36m"  -}} {{- /*green,bold*/ -}}
          {{ else if eq .Status "firing" }}
          {{-  if eq .Labels.severity "critical" -}}
          {{- $AnsiColor = "\u001b[1;31m" -}} {{- /*red,bold*/ -}} 
          {{- else -}}
          {{- $AnsiColor = "\u001b[1;33m" -}} {{- /*yellow,bold*/ -}}
          {{- end -}}
          {{- end }}
          ```ansi
          {{ $AnsiColor -}}
          Status: {{.Status}}
          Alert: {{.Labels.alertname}}
          ServiceName: {{ if .Labels.name }}{{- .Labels.name -}}{{else}}N/A{{ end }}
          Description: {{.Annotations.description}}
          Severity: {{ if .Labels.severity }}{{ .Labels.severity }}{{ else }}unknown{{ end }}
          ```

          {{- end -}}
          {{- end -}}

# see https://gist.github.com/kkrypt0nn/a02506f3712ff2d1c8ca7c9e0aed7c06 for ansi on discord