services:
  pdf_parser:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/pdf-parser:${PDF_PARSER_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    mem_limit: ${PDF_PARSER_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${PDF_PARSER_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    command: bash -c  "./setup.sh && python manage.py runserver 0.0.0.0:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      ENABLE_TRANSLATE: ${ENABLE_TRANSLATE}
      ENABLE_SUMMARIZE: ${ENABLE_SUMMARIZE}
      ENABLE_IMAGE_PARSING: ${ENABLE_IMAGE_PARSING}
      PARALLEL_FACTOR: ${PARALLEL_FACTOR}
      PDF_PARSER_MAX_RETRIES : ${PDF_PARSER_MAX_RETRIES}
      PDF_PARSER_SECRET_KEY : ${PDF_PARSER_SECRET_KEY}
      SPLIT: ${SPLIT}
      TESSDATA_PREFIX: ${TESSDATA_PREFIX}
      TORCH_DEVICE: ${TORCH_DEVICE}
      TRANSLATION_SERVICES : ${TRANSLATION_SERVICES}
    depends_on:
      - redis

  pdf_parser_celery_worker:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/pdf-parser:${PDF_PARSER_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    command: bash -c "./setup.sh && celery -A pdf_parser worker -P solo -l info"
    restart: always
    mem_limit: ${PDF_PARSER_CELERY_WORKER_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${PDF_PARSER_CELERY_WORKER_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      ENABLE_TRANSLATE: ${ENABLE_TRANSLATE}
      ENABLE_SUMMARIZE: ${ENABLE_SUMMARIZE}
      ENABLE_IMAGE_PARSING: ${ENABLE_IMAGE_PARSING}
      PARALLEL_FACTOR: ${PARALLEL_FACTOR}
      PDF_PARSER_MAX_RETRIES : ${PDF_PARSER_MAX_RETRIES}
      PDF_PARSER_SECRET_KEY : ${PDF_PARSER_SECRET_KEY}
      SPLIT: ${SPLIT}
      TESSDATA_PREFIX: ${TESSDATA_PREFIX}
      TORCH_DEVICE: ${TORCH_DEVICE}
      TRANSLATION_SERVICES : ${TRANSLATION_SERVICES}
    depends_on:
      - redis