services:
  admin:
    build:
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${org}/admin.git#${ADMIN_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      args:
        NEXT_PUBLIC_FLOWISE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/flowise
        NEXT_PUBLIC_SUPERSET_URL: ${NEXT_PUBLIC_SUPERSET_URL}
        NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL:  ${NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL}
        NEXT_PUBLIC_DATASET_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/dataset-service
        NEXT_PUBLIC_BFF_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/bff
        NEXT_PUBLIC_TELEMETRY_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/telemetry
        NEXT_PUBLIC_TRANSPORT_SOCKET_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/transport-socket
        NEXT_PUBLIC_UCI_APIS_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/uci-apis
        NEXT_PUBLIC_AUTH_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/auth-service
        NEXT_PUBLIC_DEPLOYER_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/deployer
        NEXT_PUBLIC_DOCUMENT_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/document-service
        NEXT_PUBLIC_AUTOTUNE_EXTERNAL_BASE_URL : ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/autotune
        NEXT_PUBLIC_TESTBED_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/testbed
        NEXT_PUBLIC_NODEHUB_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/nodehub
        NEXT_PUBLIC_USER_MANAGEMENT_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/user-management-service
        NEXT_PUBLIC_BROADCAST_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://${DOMAIN_NAME}/broadcast-service
        SERVE_PATH: "/admin"
    env_file:
      - ../../global.env
    environment:
      CONTEXT: ${CONTEXT}
      DESTINATION: ${DESTINATION}
      NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL: ${NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL}
      NEXT_PUBLIC_FLOWISE_URL: ${NEXT_PUBLIC_FLOWISE_URL}
      NEXT_PUBLIC_SUPERSET_URL: ${NEXT_PUBLIC_SUPERSET_URL}
    restart: always
