services:
  admin:
    build:
      context: https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${org}/admin.git#${ADMIN_GITHUB_BRANCH:-${DEFAULT_GITHUB_BRANCH:?DEFAULT_GITHUB_BRANCH is not set}}
      args:
        NEXT_PUBLIC_FLOWISE_URL: ${DOMAIN_SCHEME:-https}://flowise.${DOMAIN_NAME}
        NEXT_PUBLIC_SUPERSET_URL: ${NEXT_PUBLIC_SUPERSET_URL}
        NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL:  ${NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL}
        NEXT_PUBLIC_DATASET_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://dataset-service.${DOMAIN_NAME}
        NEXT_PUBLIC_BFF_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://bff.${DOMAIN_NAME}
        NEXT_PUBLIC_TELEMETRY_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://telemetry.${DOMAIN_NAME}
        NEXT_PUBLIC_TRANSPORT_SOCKET_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://transport-socket.${DOMAIN_NAME}
        NEXT_PUBLIC_UCI_APIS_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://uci-apis.${DOMAIN_NAME}
        NEXT_PUBLIC_AUTH_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://auth-service.${DOMAIN_NAME}
        NEXT_PUBLIC_DEPLOYER_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://deployer.${DOMAIN_NAME}
        NEXT_PUBLIC_DOCUMENT_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://document-service.${DOMAIN_NAME}
        NEXT_PUBLIC_AUTOTUNE_EXTERNAL_BASE_URL  : ${DOMAIN_SCHEME:-https}://autotune.${DOMAIN_NAME}
        NEXT_PUBLIC_TESTBED_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://testbed.${DOMAIN_NAME}
        NEXT_PUBLIC_NODEHUB_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://nodehub.${DOMAIN_NAME}
        NEXT_PUBLIC_USER_MANAGEMENT_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://user-management-service.${DOMAIN_NAME}
        NEXT_PUBLIC_BROADCAST_SERVICE_EXTERNAL_BASE_URL: ${DOMAIN_SCHEME:-https}://broadcast-service.${DOMAIN_NAME}
        SERVE_PATH: ""
    env_file:
      - ../../global.env
    environment:
      CONTEXT: ${CONTEXT}
      DESTINATION: ${DESTINATION}
      NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL: ${NEXT_PUBLIC_DIAGNOSIS_SUPERSET_URL}
      NEXT_PUBLIC_FLOWISE_URL: ${NEXT_PUBLIC_FLOWISE_URL}
      NEXT_PUBLIC_SUPERSET_URL: ${NEXT_PUBLIC_SUPERSET_URL}
    restart: always
