services:
  orchestrator:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/orchestrator:${ORCHESTRATOR_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    mem_limit: ${ORCHESTRATOR_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${ORCHESTRATOR_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    restart: always
    env_file:
      - ../../global.env
