services:
  zoho_identity_service:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/zoho-identity-service:${ZOHO_IDENTITY_SERVICE_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${ZOHO_IDENTITY_SERVICE_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${ZOHO_IDENTITY_SERVICE_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    environment:
      ZOHO_ACCESS_TOKEN: ${ZOHO_ACCESS_TOKEN}
      ZOHO_REFRESH_TOKEN: ${ZOHO_REFRESH_TOKEN}
      ZOHO_CLIENT_ID: ${ZOHO_CLIENT_ID}
      ZOHO_CLIENT_SECRET: ${ZOHO_CLIENT_SECRET}
      ZOHO_API_URL: ${ZOHO_API_URL}
