services:
  telemetry:
    image: ${DOCKER_REGISTRY_URL:-ghcr.io}/${org}/telemetry:${TELEMETRY_IMAGE_TAG:-${DEFAULT_IMAGE_TAG:?DEFAULT_IMAGE_TAG is not set}}
    restart: always
    mem_limit: ${TELEMETRY_MEM_LIMIT:-${DEFAULT_MEM_LIMIT:-256m}}
    cpus: ${TELEMETRY_CPU_LIMIT:-${DEFAULT_CPU_LIMIT:-0.5}}
    env_file:
      - ../../global.env
  