services:
  redis:
    image: redis:latest
    restart: always
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis:/data
      - redis_conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ../../global.env
    

volumes:
  redis:
  redis_conf: