services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    mem_limit: 512m
    ports:
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:?RABBITMQ_DEFAULT_USER is not set}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_DEFAULT_PASSWORD:?RABBITMQ_DEFAULT_PASSWORD is not set}

volumes:
  rabbitmq: